"""
Code Generation Quality Middleware

This middleware automatically applies quality checks and fixes to code
generated by the LLM, ensuring consistent quality and preventing common errors.
"""

import logging
import os
from typing import Dict

from app.api.v1.services.code_quality_service import CodeQualityService

logger = logging.getLogger(__name__)


class CodeGenerationQualityMiddleware:
    """
    Middleware that integrates with the code generation pipeline to automatically
    apply quality checks and fixes to generated code.
    """

    def __init__(self):
        self.quality_service = CodeQualityService()
        self.enabled_languages = ["python", "javascript", "typescript"]

    async def process_generated_files(
        self,
        project_id: str,
        generated_files: Dict[str, str],  # file_path -> content
        language: str = "python",
        auto_fix: bool = True,
    ) -> Dict[str, any]:
        """
        Process newly generated files through quality pipeline.

        Args:
            project_id: The project identifier
            generated_files: Dictionary of file_path -> file_content
            language: Programming language
            auto_fix: Whether to automatically fix issues

        Returns:
            Dictionary containing processed files and quality reports
        """
        try:
            if language not in self.enabled_languages:
                logger.warning(
                    f"Quality middleware not enabled for language: {language}"
                )
                return {
                    "processed_files": generated_files,
                    "quality_reports": {},
                    "summary": {
                        "files_processed": 0,
                        "issues_found": 0,
                        "issues_fixed": 0,
                        "quality_score": 100,
                    },
                }

            project_path = os.path.join("repos", project_id)
            processed_files = {}
            quality_reports = {}
            total_issues_found = 0
            total_issues_fixed = 0

            logger.info(
                f"Processing {len(generated_files)} generated files for quality"
            )

            for file_path, content in generated_files.items():
                # Skip non-Python files for Python-specific quality checks
                if language == "python" and not file_path.endswith(".py"):
                    logger.info(f"Skipping quality checks for non-Python file: {file_path}")
                    processed_files[file_path] = content
                    quality_reports[file_path] = {
                        "skipped": True,
                        "reason": "Non-Python file, skipped Python quality checks."
                    }
                    continue
                try:
                    # Apply quality improvements
                    quality_report = await self.quality_service.improve_generated_code(
                        code=content,
                        file_path=file_path,
                        language=language,
                        project_dir=project_path,
                    )

                    # Use improved code if auto_fix is enabled
                    final_content = quality_report.fixed_code if auto_fix else content
                    processed_files[file_path] = final_content

                    # Store quality report
                    quality_reports[file_path] = {
                        "issues_found": len(quality_report.issues_found),
                        "issues_fixed": len(quality_report.issues_fixed),
                        "remaining_issues": len(quality_report.remaining_issues),
                        "result": quality_report.result.value,
                        "tools_used": quality_report.tools_used,
                        "execution_time": quality_report.execution_time,
                        "improvements_applied": quality_report.fixed_code != content,
                    }

                    total_issues_found += len(quality_report.issues_found)
                    total_issues_fixed += len(quality_report.issues_fixed)

                    logger.info(
                        f"Quality check completed for {file_path}: "
                        f"{len(quality_report.issues_found)} issues found, "
                        f"{len(quality_report.issues_fixed)} fixed"
                    )

                except Exception as e:
                    logger.error(f"Error processing file {file_path}: {str(e)}")
                    processed_files[file_path] = content  # Use original content
                    quality_reports[file_path] = {
                        "error": str(e),
                        "issues_found": 0,
                        "issues_fixed": 0,
                        "remaining_issues": 1,  # The error itself
                    }

            # Calculate quality score
            quality_score = self._calculate_quality_score(
                total_issues_found, total_issues_fixed
            )

            return {
                "processed_files": processed_files,
                "quality_reports": quality_reports,
                "summary": {
                    "files_processed": len(generated_files),
                    "issues_found": total_issues_found,
                    "issues_fixed": total_issues_fixed,
                    "remaining_issues": total_issues_found - total_issues_fixed,
                    "quality_score": quality_score,
                    "auto_fix_enabled": auto_fix,
                },
            }

        except Exception as e:
            logger.error(f"Error in quality middleware: {str(e)}", exc_info=True)
            return {
                "processed_files": generated_files,  # Return original files
                "quality_reports": {},
                "summary": {
                    "files_processed": 0,
                    "issues_found": 0,
                    "issues_fixed": 0,
                    "quality_score": 0,
                    "error": str(e),
                },
            }

    async def validate_before_writing(
        self, project_id: str, file_path: str, content: str, language: str = "python"
    ) -> Dict:
        """
        Validate code before writing to filesystem.

        Args:
            project_id: The project identifier
            file_path: Path where the file will be written
            content: File content to validate
            language: Programming language

        Returns:
            Validation result with recommendations
        """
        try:
            if language not in self.enabled_languages:
                return {
                    "valid": True,
                    "warnings": [],
                    "errors": [],
                    "recommendations": [],
                }

            project_path = os.path.join("repos", project_id)

            # Run quality check without fixing
            quality_report = await self.quality_service.improve_generated_code(
                code=content,
                file_path=file_path,
                language=language,
                project_dir=project_path,
            )

            # Categorize issues
            errors = [
                issue
                for issue in quality_report.issues_found
                if issue.get("severity", "").lower() in ["error", "critical"]
            ]
            warnings = [
                issue
                for issue in quality_report.issues_found
                if issue.get("severity", "").lower() in ["warning", "medium"]
            ]

            # Generate recommendations
            recommendations = []
            if quality_report.issues_fixed:
                recommendations.append(
                    "Consider applying automatic fixes for style and formatting issues"
                )
            if errors:
                recommendations.append("Critical errors found - manual review required")
            if len(quality_report.remaining_issues) > 5:
                recommendations.append(
                    "Consider running comprehensive linting before deployment"
                )

            return {
                "valid": len(errors) == 0,
                "warnings": warnings,
                "errors": errors,
                "recommendations": recommendations,
                "quality_score": self._calculate_quality_score(
                    len(quality_report.issues_found), len(quality_report.issues_fixed)
                ),
                "fixable_issues": len(quality_report.issues_fixed),
                "total_issues": len(quality_report.issues_found),
            }

        except Exception as e:
            logger.error(f"Error in validation: {str(e)}", exc_info=True)
            return {
                "valid": False,
                "warnings": [],
                "errors": [{"type": "validation_error", "message": str(e)}],
                "recommendations": ["Manual review required due to validation failure"],
            }

    async def setup_project_quality_config(
        self, project_id: str, language: str = "python"
    ) -> Dict:
        """
        Set up quality configuration files for a project.

        Args:
            project_id: The project identifier
            language: Programming language

        Returns:
            Configuration setup results
        """
        try:
            project_path = os.path.join("repos", project_id)

            if not os.path.exists(project_path):
                raise ValueError(f"Project directory not found: {project_path}")

            config_files = {}

            if language == "python":
                # Create pyproject.toml with quality tool configurations
                pyproject_config = self._generate_python_quality_config()
                config_path = os.path.join(project_path, "pyproject.toml")

                # Check if pyproject.toml exists
                if os.path.exists(config_path):
                    with open(config_path, "r") as f:
                        existing_content = f.read()

                    # Only add if quality configurations don't exist
                    if "[tool.black]" not in existing_content:
                        with open(config_path, "a") as f:
                            f.write("\n" + pyproject_config)
                        config_files["pyproject.toml"] = "updated"
                    else:
                        config_files["pyproject.toml"] = "exists"
                else:
                    with open(config_path, "w") as f:
                        f.write(pyproject_config)
                    config_files["pyproject.toml"] = "created"

                # Create .flake8 configuration
                flake8_config = self._generate_flake8_config()
                flake8_path = os.path.join(project_path, ".flake8")
                if not os.path.exists(flake8_path):
                    with open(flake8_path, "w") as f:
                        f.write(flake8_config)
                    config_files[".flake8"] = "created"
                else:
                    config_files[".flake8"] = "exists"

            elif language in ["javascript", "typescript"]:
                # Create prettier configuration
                prettier_config = self._generate_prettier_config()
                prettier_path = os.path.join(project_path, ".prettierrc")
                if not os.path.exists(prettier_path):
                    with open(prettier_path, "w") as f:
                        f.write(prettier_config)
                    config_files[".prettierrc"] = "created"

            return {
                "success": True,
                "language": language,
                "config_files": config_files,
                "project_path": project_path,
            }

        except Exception as e:
            logger.error(f"Error setting up quality config: {str(e)}", exc_info=True)
            return {"success": False, "error": str(e), "config_files": {}}

    def _calculate_quality_score(self, issues_found: int, issues_fixed: int) -> int:
        """Calculate a quality score based on issues found and fixed."""
        if issues_found == 0:
            return 100

        fix_rate = issues_fixed / issues_found if issues_found > 0 else 0
        base_score = max(0, 100 - (issues_found * 5))  # Deduct 5 points per issue
        bonus = fix_rate * 20  # Bonus for fixes

        return min(100, int(base_score + bonus))

    def _generate_python_quality_config(self) -> str:
        """Generate Python quality tool configuration."""
        return '''
# Code quality tool configurations
[tool.black]
line-length = 88
target-version = ['py311']
include = '\\.pyi?$'
extend-exclude = """
/(
  migrations
  | __pycache__
  | .git
  | .pytest_cache
)/
"""

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.ruff]
line-length = 88
target-version = "py311"
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
ignore = [
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
ignore_missing_imports = true
'''

    def _generate_flake8_config(self) -> str:
        """Generate flake8 configuration."""
        return """[flake8]
max-line-length = 88
extend-ignore = E203, E266, E501, W503
max-complexity = 10
select = B,C,E,F,W,T4,B9
exclude =
    migrations,
    __pycache__,
    .git,
    .pytest_cache,
    venv,
    env
"""

    def _generate_prettier_config(self) -> str:
        """Generate Prettier configuration."""
        return """{
  "semi": true,
  "trailingComma": "es5",
  "singleQuote": true,
  "printWidth": 80,
  "tabWidth": 2
}
"""
